name: Build and Deploy
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    env:
      REMOTE_TARGET: ${{ vars.REMOTE_TARGET }}
      SERVER_PORT: ${{ vars.SERVER_PORT }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package -DskipTests=true

      - name: Testa variável
        run: echo $REMOTE_TARGET

#      - name: Run Tests
#        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test
#      - name: Report
#        uses: dorny/test-reporter@v1
#        if: always()
#        with:
#          name: Maven Tests
#          path: target/surefire-reports/*.xml
#          reporter: java-junit
#          fail-on-error: true

      - name: Deploy JAR to VPS
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_SERVER_DIY_COMPANY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "target/api-expense-track.jar"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: $REMOTE_TARGET

      - name: Deploy DOCKERFILE to VPS
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_SERVER_DIY_COMPANY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "dev.Dockerfile"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: $REMOTE_TARGET

      - name: Run container
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY_SERVER_DIY_COMPANY }}
          port: ${{ secrets.REMOTE_PORT }}
          script: |
            CONTAINER_NAME="api-expense-track-dev"
            IMAGE_NAME="api-expense-track-dev-img"
            REMOTE_TARGET= ${{ vars.REMOTE_TARGET }}
            NETWORK_NAME="bridge"
            DATABASE_HOST="postgresql://${{ secrets.REMOTE_HOST }}:${{ secrets.REMOTE_DATABASE_PORT }}/${{ secrets.REMOTE_DATABASE_NAME }}"
            DATABASE_USER="${{ secrets.REMOTE_DATABASE_USER }}"
            DATABASE_PASSWORD="${{ secrets.REMOTE_DATABASE_PASSWORD }}"
            JAR_FILE_PATH="$REMOTE_TARGET/api-expense-track.jar"
            PATH_DOCKERFILE=$REMOTE_TARGET/dev.Dockerfile
            EXPENSE_TRACK_JWT_SECRET=${{ secrets.EXPENSE_TRACK_JWT_SECRET }}
            TZ="America/Sao_Paulo"
            if [ "$(docker ps -a -q -f name=$CONTAINER_NAME)" ]; then
              echo "Parando e removendo o contêiner existente..."
              docker stop $CONTAINER_NAME
              docker rm $CONTAINER_NAME
              sh apis/scripts/remove_image.sh -n $IMAGE_NAME
            else
              echo "Nenhum contêiner com o nome $CONTAINER_NAME encontrado."
            fi
            
            docker build -t $IMAGE_NAME $PATH_DOCKERFILE
            docker run -d --name $CONTAINER_NAME --network $NETWORK_NAME -p $SERVER_PORT:$SERVER_PORT -v $JAR_FILE_PATH:/app/api-expense-track.jar -e DATABASE_HOST=$DATABASE_HOST -e DATABASE_USER=$DATABASE_USER -e DATABASE_PASSWORD=$DATABASE_PASSWORD -e expense.track.jwt.secret=$EXPENSE_TRACK_JWT_SECRET -e TZ=$TZ -e server.port=$SERVER_PORT $IMAGE_NAME